package com.ketroc.strategies;

public enum GamePlan {
    BANSHEE,
    BANSHEE_CYCLONE,
    ONE_BASE_BANSHEE_CYCLONE,
    BANSHEE_TANK,
    TANK_VIKING,
    ONE_BASE_TANK_VIKING,
    BUNKER_CONTAIN_WEAK,
    BUNKER_CONTAIN_STRONG,
    RAVEN,
    MARINE_RUSH,
    SCV_RUSH,
    RAVEN_CYCLONE,
    MASS_MINE_OPENER,
    GHOST_HELLBAT,
    MECH_ALL_IN,
    BC_RUSH,
    NONE;
}
