package com.ketroc.utils;

public final class MapNames {
    public static final String ACROPOLIS = "Acropolis LE";
    public static final String ASCENSION_TO_AIUR = "Ascension to Aiur LE";
    public static final String CATALYST = "Catalyst LE";
    public static final String DEATH_AURA = "Deathaura LE";
    public static final String DEATH_AURA505 = "Deathaura 5.0.5";
    public static final String DEATH_AURA506 = "Deathaura 5.0.6";
    public static final String DISCO_BLOODBATH = "Disco Bloodbath LE";
    public static final String EPHEMERON = "[TLMC12] Ephemeron";
    public static final String EPHEMERONLE = "Ephemeron LE";
    public static final String ETERNAL_EMPIRE = "Eternal Empire LE";
    public static final String ETERNAL_EMPIRE505 = "Eternal Empire 5.0.5";
    public static final String ETERNAL_EMPIRE506 = "Eternal Empire 5.0.6";
    public static final String EVER_DREAM = "Ever Dream LE";
    public static final String EVER_DREAM505 = "Ever Dream 5.0.5";
    public static final String EVER_DREAM506 = "Ever Dream 5.0.6";
    public static final String GOLDEN_WALL = "Golden Wall LE";
    public static final String GOLDEN_WALL505 = "Golden Wall 5.0.5";
    public static final String GOLDEN_WALL506 = "Golden Wall 5.0.6";
    public static final String ICE_AND_CHROME = "Ice and Chrome LE";
    public static final String ICE_AND_CHROME505 = "Ice and Chrome LE 5.0.5";
    public static final String ICE_AND_CHROME506 = "Ice and Chrome 5.0.6";
    public static final String JAGANNATHA = "Jagannatha LE";
    public static final String LIGHTSHADE = "Lightshade LE";
    public static final String NIGHTSHADE = "Nightshade LE";
    public static final String OXIDE = "Oxide LE";
    public static final String PILLARS_OF_GOLD = "Pillars of Gold LE";
    public static final String PILLARS_OF_GOLD505 = "Pillars of Gold LE 5.0.5";
    public static final String PILLARS_OF_GOLD506 = "Pillars of Gold 5.0.6";
    public static final String ROMANTICIDE = "Romanticide LE";
    public static final String SIMULACRUM = "Simulacrum LE";
    public static final String SUBMARINE = "Submarine LE";
    public static final String SUBMARINE505 = "Submarine LE 5.0.5";
    public static final String SUBMARINE506 = "Submarine 5.0.6";
    public static final String THUNDERBIRD = "Thunderbird LE";
    public static final String TRITON = "Triton LE";
    public static final String WINTERS_GATE = "Winter's Gate LE";
    public static final String WORLD_OF_SLEEPERS = "World of Sleepers LE";
    public static final String ZEN = "Zen LE";
}
